name: ARCcrop
options:
  bundleIdPrefix: com.arccrop
  deploymentTarget:
    iOS: "18.0"
    tvOS: "18.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "6.0"

targets:
  ARCcrop:
    type: application
    platform: iOS
    sources:
      - path: ARCcrop
        excludes:
          - "**/.*"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arccrop.app
        INFOPLIST_FILE: ARCcrop/Info.plist
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: true
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: ARCcrop/Info.plist
      properties:
        UILaunchScreen: {}

  ARCcropTV:
    type: application
    platform: tvOS
    sources:
      - path: ARCcrop/App
      - path: ARCcrop/Views
      - path: ARCcrop/Models
      - path: ARCcrop/Services
      - path: ARCcrop/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arccrop.app.tv
        INFOPLIST_FILE: ARCcropTV/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: ARCcropTV/Info.plist
      properties:
        UILaunchScreen: {}
